// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtO114aZBn_aq7-f7-UNNJSO8liaumsYI',
    appId: '1:156750507020:web:afcf2c66c1ece5e9821229',
    messagingSenderId: '156750507020',
    projectId: 'arafa-3dd97',
    authDomain: 'arafa-3dd97.firebaseapp.com',
    storageBucket: 'arafa-3dd97.appspot.com',
    measurementId: 'G-J7ZW77M19D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxCb8xJXHfJtIddsgVzSFiugbB_JV370',
    appId: '1:156750507020:android:bec9d3414a934915821229',
    messagingSenderId: '156750507020',
    projectId: 'arafa-3dd97',
    storageBucket: 'arafa-3dd97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtcKFy4XJscIX6qbb2_j0_FkRgKXMKI4',
    appId: '1:156750507020:ios:52a5b2fb01d50181821229',
    messagingSenderId: '156750507020',
    projectId: 'arafa-3dd97',
    storageBucket: 'arafa-3dd97.appspot.com',
    iosClientId: '156750507020-tb1rsqul15u0aev097eui68i6rk4lsl2.apps.googleusercontent.com',
    iosBundleId: 'com.example.arafa',
  );
}
